### ISSUE TITLE
AttributeError: type object '_io.StringIO' has no attribute 'StringIO' trying request again in 5 seconds

### ISSUE THREAD

**Issue by osmtools** [fossgis/usergroups-bot#7]
Der Output vom cronjob via Mail enthält folgenden Inhalt:
```
Traceback (most recent call last):
  File "/home/haraldhartmann/usergroups-bot/wikitools3/api.py", line 298, in __parseJSON
    parsed = json.loads(data.read())
  File "/usr/lib/python3.9/json/__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/haraldhartmann/usergroups-bot/wiki2users.py", line 77, in <module>
    groups = osmwiki.loadAllUserGroups(user, password)
  File "/home/haraldhartmann/usergroups-bot/osmwiki.py", line 20, in loadAllUserGroups
    __loginSite(user, password)
  File "/home/haraldhartmann/usergroups-bot/osmwiki.py", line 30, in __loginSite
    site = wiki.Wiki(["https://wiki.openstreetmap.org/w/api.php"](https://wiki.openstreetmap.org/w/api.php))
  File "/home/haraldhartmann/usergroups-bot/wikitools3/wiki.py", line 106, in __init__
    self.setSiteinfo()
  File "/home/haraldhartmann/usergroups-bot/wikitools3/wiki.py", line 125, in setSiteinfo
    info = req.query(False)
  File "/home/haraldhartmann/usergroups-bot/wikitools3/api.py", line 168, in query
    data = self.__parseJSON(rawdata)
  File "/home/haraldhartmann/usergroups-bot/wikitools3/api.py", line 323, in __parseJSON
    data.seek(0)
io.UnsupportedOperation: seek
```

**Comment by osmtools** [comment]
Der Fehler kommt bereits beim Aufruf der allgemeinen API:
```
>>> from wikitools3 import wiki
>>> from wikitools3 import api
>>> site = wiki.Wiki("https://wiki.openstreetmap.org/w/api.php")
AttributeError: type object '_io.StringIO' has no attribute 'StringIO' trying request again in 5 seconds
```

**Comment by osmtools** [comment]
@Nakaner ist dir etwas bekannt, ob es beim Webserver von wiki.openstreetmap.org eine Änderung gab? _z.B. das nur noch GZIP ausgeliefert wird, obwohl das eigentlich von der wikitools3 lib gehandelt wird?!_
Wenn oder wo könnte ich da weiter fragen?

**Comment by osmtools** [comment]
Anscheinend ist gzip das Problem. Wenn man in wikitools3/api.py gzip auf False setzt, läuft der Bot sauber durch.
